### ISSUE TITLE
Manual sources don't works.

### ISSUE THREAD

**Issue by WarC0zes** [abualy/philips-tv-remote-card#1]
Hi,
using the sources manually, it does not work. With the default sources it works, at least netflix.
I really appreciate your card and would be nice to fix this problem.
I've a Philips 55OLED854.

my source code:
```
                      sources:
                        - icon: mdi:netflix
                          url: com.netflix.ninja.MainActivity-com.netflix.ninja
                        - icon: phu:prime-video
                          url: >-
                            com.amazon.ignition.IgnitionActivity-com.amazon.amazonvideo.livingroom
                        - icon: mdi:plus-thick
                          url: >-
                            com.canal.ui.tv.TvMainActivity-com.canal.android.canal
                        - icon: phu:disney-plus
                          url: >-
                            com.bamtechmedia.dominguez.main.MainActivity-com.disney.disneyplus
                        - icon: mdi:kodi
                          url: >-
                            net.kodinerds.maven.kodi.Splash-net.kodinerds.maven.kodi
                        - icon: mdi:youtube
                          url: >-
                            com.google.android.apps.youtube.tv.activity.ShellActivity-com.google.android.youtube.tv
```
